
local Tunnel = module("vrp", "lib/Tunnel")
local Proxy = module("vrp", "lib/Proxy")

vRP = Proxy.getInterface("vRP")
vRPclient = Tunnel.getInterface("vRP","vRP_jobs")

vRPpp = nil
TriggerEvent('vRP:getSharedObject', function(obj) 
	vRPpp = obj 
end)

RegisterServerEvent('vRP:setTaxi')
AddEventHandler('vRP:setTaxi', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Taximetrist"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Taximetrist!",})
end)

RegisterServerEvent('vRP:setMechanic')
AddEventHandler('vRP:setMechanic', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Mechanic"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Mecannic!",})
end)

RegisterServerEvent('vRP:setConstructor')
AddEventHandler('vRP:setConstructor', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Constructor"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Constructor!",})
end)

RegisterServerEvent('vRP:setMiner')
AddEventHandler('vRP:setMiner', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Miner"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Miner!",})
end)

RegisterServerEvent('vRP:setDelivery')
AddEventHandler('vRP:setDelivery', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Delivery"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Delivery!",})
end)

RegisterServerEvent('vRP:setBankdriver')
AddEventHandler('vRP:setBankdriver', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Bankdriver"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Bankdriver!",})
end)

RegisterServerEvent('vRP:setFAN_COURIER')
AddEventHandler('vRP:setFAN_COURIER', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "FAN COURIER"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~FAN COURIER!",})
end)

RegisterServerEvent('vRP:setPizza')
AddEventHandler('vRP:setPizza', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Pizza"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Pizza!",})
end)

RegisterServerEvent('vRP:setMedical')
AddEventHandler('vRP:setMedical', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Medical Transport"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Medical Transport!",})
end)

RegisterServerEvent('vRP:setEscorta')
AddEventHandler('vRP:setEscorta', function(job)
	local user_id = vRP.getUserId({source})
    local player = vRP.getUserSource({user_id})
	vRP.addUserGroup({user_id, "Escorta"})
	vRPclient.notifyPicture(user_id,{"CHAR_ALL_PLAYERS_CONF",1, "JOBS", false,"Ai fost angajat ca ~g~Escorta!",})
end)
